
about :

  name : 'wConsequence'
  description : 'Advanced synchronization mechanism. Asynchronous routines may use Consequence to wrap postponed result, what allows classify callback for such routines as output, not input, what improves analyzability of a program. Consequence may be used to make a queue for mutually exclusive access to a resource. Algorithmically speaking Consequence is 2 queues ( FIFO ) and a customizable arbitrating algorithm. The first queue contains available resources, the second queue includes competitors for this resources. At any specific moment, one or another queue may be empty or full. Arbitrating algorithm makes resource available for a competitor as soon as possible. There are 2 kinds of resource: regular and erroneous. Unlike Promise, Consequence is much more customizable and can solve engineering problem which Promise cant. But have in mind with great power great responsibility comes. Consequence can coexist and interact with a Promise, getting fulfillment/rejection of a Promise or fulfilling it. Use Consequence to get more flexibility and improve readability of asynchronous aspect of your application.'
  version : '0.5.0'
  enabled : 1
  interpreters :
  - njs >= 10.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools
  - Callback
  - Event
  - Signal
  - Mutex
  - Semaphore
  - Async
  - Promise
  license : MIT
  author : 'Kostiantyn Wandalen <wanalen@01.school>'
  contributors :
  - 'Kostiantyn Wandalen <wanalen@01.school>'
  - 'Volodymyr M. <volodymyr.migdal@gmail.com>'
  - 'Ihor O. <iostashvxi@gmail.com>'
  npm.name : 'wConsequence'
  npm.scripts :
    test : 'wtest .run proto/**'
    docgen : 'wdocgen .build proto'

path :

  repository : git+https:///github.com/Wandalen/wConsequence.git
  origins :
   - git+https:///github.com/Wandalen/wConsequence.git
   - npm:///wConsequence
  bugtracker : https:///github.com/Wandalen/wConsequence/issues

step :

  proto.export :
    inherit : module.export
    export : path::export
    tar : 0
    criterion :
      content : 'proto'

  doc.export :
    inherit : module.export
    export : path::doc
    tar : 0
    criterion :
      content : 'doc'

  npm.export :
    inherit : module.export
    export : out.npm
    tar : 0
    criterion :
      content : 'npm'

  npm.publish :
    shell : npm publish

build :

  proto.export :
    criterion :
      content : 'proto'
      export : 1
    steps :
      # - build::debug.raw
      - step::proto.export

  doc.export :
    criterion :
      content : 'doc'
      export : 1
    steps :
      # - build::debug.raw
      - step::doc.export

  npm.export :
    criterion :
      content : 'npm'
      export : 1
    steps :
      # - build::debug.raw
      # - step::npm.export
      - step::npm.publish

  export :

    criterion :
      default : 1
      export : 1
    steps :
      # - build::npm
      - build::proto.export
      # - build::doc.export
